language: python
sudo: true
python: 3.6
install:
  - sudo apt-get install enchant myspell-en-gb
  - pip install -Ur src/requirements/documentation.txt
  - cd src/
  - pip install -U pip setuptools wheel typing codecov coverage
  - pip install -Ur requirements/dev.txt -r requirements/fancy.txt
  - pip install -Ur requirements.txt
script:
  - python manage.py collectstatic --noinput
  - python manage.py compress
  - python manage.py compilemessages
  - pylama
  - isort -rc -c .
  - py.test --cov=pretalx tests/ && codecov
  - pip list -o --format=columns
  - cd ../doc && make spelling
